// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: leader-board.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUserToLeaderBoard = `-- name: AddUserToLeaderBoard :exec
INSERT INTO leader_board (id, best_time, user_id)
VALUES ($1, $2, $3)
`

type AddUserToLeaderBoardParams struct {
	ID       uuid.UUID
	BestTime string
	UserID   uuid.UUID
}

func (q *Queries) AddUserToLeaderBoard(ctx context.Context, arg AddUserToLeaderBoardParams) error {
	_, err := q.db.ExecContext(ctx, addUserToLeaderBoard, arg.ID, arg.BestTime, arg.UserID)
	return err
}
