// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
)

type LeaderBoard struct {
	ID       uuid.UUID
	BestTime string
	UserID   uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
}
